# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel
sudo: false
cache: packages

r_packages:
  - knitr
  - glmnet
  - MASS
  - Matrix
  - progress
  - magrittr

after_success:
  - Rscript -e 'library(covr); codecov()'

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY", ""))'
  # script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true

notifications:
  email:
    - sahir.bhatnagar@gmail.com

r_github_packages:
    - OchoaLab/simtrait
