# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel
sudo: false
cache: packages

r_packages:
  - knitr
  - glmnet
  - MASS
  - Matrix
  - progress
  - magrittr

after_success:
  - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    - sahir.bhatnagar@gmail.com

r_github_packages:
    - OchoaLab/simtrait
